Here are some edits I've made so far. I haven't been able to test them, the files won't compile because it gives a fatal error for hashmap.h not existing or says undefined reference to the tokenize function.